# Generated by Django 4.1.3 on 2023-01-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='has_nested_data',
        ),
        migrations.RemoveField(
            model_name='level',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='level',
            name='link',
        ),
        migrations.RemoveField(
            model_name='level',
            name='page',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
